### ISSUE TITLE
[BUG] Error at load 2

### ISSUE THREAD

**Issue by JamesGalt** [ilgizar/ilgizar-candlestick-panel#10]
I use the 5.0.0 version now
Datasource is influxdb for all queries
I have `undefined is not an object (evaluating 'this.panel.seriesOverrides')` on safari macOS

and
```
TypeError: Cannot set property '0' of undefined
    at CandleStickCtrl.refreshColors (http://localhost:3010/public/plugins/ilgizar-candlestick-panel/candlestick_ctrl.js:285:53)
    at CandleStickCtrl.onDataReceived (http://localhost:3010/public/plugins/ilgizar-candlestick-panel/candlestick_ctrl.js:263:18)
```
on chrome macOS

[EDIT] Can you give me a working json panel? it may help to debug. thx

Thanks

**Comment by ilgizar** [comment]
Strangely, I'll see what the problem is.

**Comment by JamesGalt** [comment]
Fix confirmed 🥇
