### ISSUE TITLE
[Bug] Error at load

### ISSUE THREAD

**Issue by JamesGalt** [ilgizar/ilgizar-candlestick-panel#8]
I am using simpleJson data source for indicators seems that there is no alias for the metrics coming from this data source.
[see here](https://github.com/grafana/simple-json-datasource/issues/50)

[EDIT] - I have the same problem with influxdb datasource indicators

[EDIT1] - Do you think it is related to grafana version? I'm using `Version 4.6.3 (commit: 7a06a47)`

`undefined is not an object (evaluating 'this.panel.aliasColors[this.series[i].alias]')`

Stack trace

```
refreshColors

onDataReceived
onDataReceived@[native code]
emit@http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:15:520753
emit@http://localhost:3010/public/build/app.5331f559bd9a1bed9a93.js:1:29221
handleQueryResult@http://localhost:3010/public/build/0.be20b78823b4c9d93a84.js:7:19864
[native code]
u@http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:68723
http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:69128
$digest@http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:74825
$apply@http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:76645
http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:72703
i@http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:21875
http://localhost:3010/public/build/vendor.2305a8e1d478628b1297.js:43:23333
```

**Comment by JamesGalt** [comment]
@ilgizar any idea on this? Thanks :)

**Comment by ilgizar** [comment]
I recommend use version 5.0.0 released 1 march 2018.

**Comment by JamesGalt** [comment]
@ilgizar 
I have `undefined is not an object (evaluating 'this.panel.seriesOverrides')` on both 4.6.3 and 5.0.0 on safari

and
```
TypeError: Cannot set property '0' of undefined
    at CandleStickCtrl.refreshColors (http://localhost:3010/public/plugins/ilgizar-candlestick-panel/candlestick_ctrl.js:285:53)
    at CandleStickCtrl.onDataReceived (http://localhost:3010/public/plugins/ilgizar-candlestick-panel/candlestick_ctrl.js:263:18)
```
 on  5.0.0 on chrome
